name: Deploy

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]
jobs:
  build:
      runs-on: ubuntu-latest
      permissions: read-all
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup nodejs
          uses: actions/setup-node@v2
          with:
            node-version: "17"
        - name: Install packages
          run: npm install
        - name: Build Vue application
          run: npm run build
  deploy:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Deploy Github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: ./docs
